export const ResponseConstants = {
    INTERNAL_SERVER_ERROR: 'Internal Server Error',
    EMAIL_ALREADY_EXISTS: 'This email already exists!',
    WRONG_CREDENTIALS: 'Looks like the email or password is incorrect.',
    FORBIDDEN_ACCESS: 'You\'re not allowed!',
    LOGIN_SUCCESS: 'Logged in successfully!',
    MISSING_TOKEN: 'The token is missing',
    INVALID_TOKEN: 'The token is invalid!',
    INVALID_USER: 'Have we met somewhere?',
    ADD_QUESTION_SUCCESS: 'Question Added Successfully',
    QUESTION_NOT_FOUND: 'Question not found',
    QUESTIONS_FETCH_SUCCESS: 'Questions fetched successfully!',
    UPDATE_QUESTION_SUCCESS: 'Question updated successfully',
    GET_QUESTION_SUCCESS: 'Question Fetched successfully',
    DELETE_QUESTION_SUCCESS: 'Question deleted successfully',
    ADD_CANDIDATE_SUCCESS: 'Candidate added successfully',
    FETCH_CANDIDATES_SUCCESS: 'All candidates fethced successfully',
    CANDIDATE_NOT_FOUND: 'Candidate not found',
    FETCH_CANDIDATE_SUCCESS: 'Candidate fetched successfully',
    UPDATE_CANDIDATE_SUCCESS: 'Candidate updated successfully',
    CANDIDATE_DELETE_SUCCESS: 'Candidate deleted successfully'
}
