export const StatusCodes = {
    HTTP_OK: 200,
    HTTP_CREATED: 201,
    HTTP_INTERNAL_SERVER_ERROR: 500,
    HTTP_NOT_FOUND: 404,
    HTTP_UNPROCESSABLE_ENTITY: 422,
    HTTP_BAD_REQUEST: 400,
    HTTP_FORBIDDEN: 403
}